import os

RUN_LEGACY_STRATEGY = False
PHASE_A_DATA_ENGINE_ONLY = False
SIGNALS_ENABLED = True
TELEGRAM_ENABLED = True
PUSHER_ENABLED = True

DERIV_APP_ID = 1089
DERIV_WS_URL = f"wss://ws.derivws.com/websockets/v3?app_id={DERIV_APP_ID}"
DERIV_PING_INTERVAL_SECONDS = 25
DERIV_RECONNECT_MAX_BACKOFF = 32

TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "")

PUSHER_APP_ID = os.environ.get("PUSHER_APP_ID", "")
PUSHER_KEY = os.environ.get("PUSHER_KEY", "")
PUSHER_SECRET = os.environ.get("PUSHER_SECRET", "")
PUSHER_CLUSTER = os.environ.get("PUSHER_CLUSTER", "ap2")

CANDLE_HISTORY_LIMIT = 200
STALE_TICK_THRESHOLD_SEC = 25.0
SERVER_SYNC_TOLERANCE_SEC = 3.0
SIGNAL_THRESHOLD_CALL_PUT = 8
SIGNAL_THRESHOLD_WATCH = 5
HYPOTHETICAL_EXPIRY_SECONDS = 60
DB_PATH = "signal_board.db"
TIMEZONE_NAME = "Asia/Dhaka"

# Strategy safety gates. These deliberately prefer fewer, cleaner signals.
MIN_1M_HISTORY = 60
MIN_5M_HISTORY = 60
MIN_15M_HISTORY = 25
MIN_ADX_5M = 20.0
RSI_CALL_MIN = 55.0
RSI_CALL_MAX = 70.0
RSI_PUT_MIN = 30.0
RSI_PUT_MAX = 45.0
# 15M is context only; 5M structure and 1M entry remain mandatory.
REQUIRE_15M_ALIGNMENT = False
REQUIRE_5M_1M_ALIGNMENT = True
REQUIRE_CURRENT_CANDLE_CONFIRMATION = True

# Pair-selection controls.
SAME_PAIR_COOLDOWN_MINUTES = 0
ALLOW_NEXT_PAIR_DURING_COOLDOWN = True

FOREX_PAIRS = {
    "frxEURUSD": "EUR/USD",
    "frxGBPUSD": "GBP/USD",
    "frxUSDJPY": "USD/JPY",
    "frxUSDCHF": "USD/CHF",
    "frxAUDUSD": "AUD/USD",
    "frxUSDCAD": "USD/CAD",
    "frxNZDUSD": "NZD/USD",
    "frxEURJPY": "EUR/JPY",
    "frxGBPJPY": "GBP/JPY",
    "frxEURGBP": "EUR/GBP",
    "frxEURCHF": "EUR/CHF",
    "frxGBPCHF": "GBP/CHF",
    "frxAUDJPY": "AUD/JPY",
    "frxCADJPY": "CAD/JPY",
    "frxCHFJPY": "CHF/JPY",
    "frxAUDCAD": "AUD/CAD",
}
