import os

RUN_LEGACY_STRATEGY = False
PHASE_A_DATA_ENGINE_ONLY = False
SIGNALS_ENABLED = True
TELEGRAM_ENABLED = True
PUSHER_ENABLED = True

DERIV_APP_ID = 1089
DERIV_WS_URL = f"wss://ws.derivws.com/websockets/v3?app_id={DERIV_APP_ID}"
DERIV_PING_INTERVAL_SECONDS = 25
DERIV_RECONNECT_MAX_BACKOFF = 32

TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "8893372314:AAEIf8UbuT1_WMYfqPTBpXCtWJLEmrvJIR4")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "-1004489990906")

PUSHER_APP_ID = os.environ.get("PUSHER_APP_ID", "2190746")
PUSHER_KEY = os.environ.get("PUSHER_KEY", "f6d226d63552173e92b9")
PUSHER_SECRET = os.environ.get("PUSHER_SECRET", "0ab61f388d482d06c232")
PUSHER_CLUSTER = os.environ.get("PUSHER_CLUSTER", "ap2")

CANDLE_HISTORY_LIMIT = 200
STALE_TICK_THRESHOLD_SEC = 25.0
SERVER_SYNC_TOLERANCE_SEC = 3.0
SIGNAL_THRESHOLD_CALL_PUT = 6
SIGNAL_THRESHOLD_WATCH = 5
HYPOTHETICAL_EXPIRY_SECONDS = 60
DB_PATH = "signal_board.db"
TIMEZONE_NAME = "Asia/Dhaka"

FOREX_PAIRS = {
    "frxEURUSD": "EUR/USD",
    "frxGBPUSD": "GBP/USD",
    "frxUSDJPY": "USD/JPY",
    "frxUSDCHF": "USD/CHF",
    "frxAUDUSD": "AUD/USD",
    "frxUSDCAD": "USD/CAD",
    "frxNZDUSD": "NZD/USD",
    "frxEURJPY": "EUR/JPY",
    "frxGBPJPY": "GBP/JPY",
    "frxEURGBP": "EUR/GBP",
    "frxEURCHF": "EUR/CHF",
    "frxGBPCHF": "GBP/CHF",
    "frxAUDJPY": "AUD/JPY",
    "frxCADJPY": "CAD/JPY",
    "frxCHFJPY": "CHF/JPY",
    "frxAUDCAD": "AUD/CAD",
}
